language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
before_install:
  # TODO: Can thse be in addons without sudo for faster builds?
  - sudo apt-get -qq update
  - sudo apt-get install -y freeglut3-dev
install:
  # SDL2
  - curl -O http://www.libsdl.org/release/SDL2-2.0.5.tar.gz
  - tar -xzvf SDL2-2.0.5.tar.gz
  - (cd SDL2-2.0.5 && ./configure && make && sudo make install)
script:
  - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - gcc -v && g++ -v && cmake --version
  - "./config.sh"
  - cd build
  - make
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-6
      - gcc-6