language: cpp
sudo: required
compiler:
    - gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y freeglut3-dev
install:
  # SDL2
  - curl -O http://www.libsdl.org/release/SDL2-2.0.5.tar.gz
  - tar -xzvf SDL2-2.0.5.tar.gz
  - (cd SDL2-2.0.5 && ./configure && make && sudo make install)
script:
  - "./config.sh"
  - cd build
  - make
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test # g++ 5
    packages:
      - cmake
      - cmake-data
      - gcc-5
      - g++-5