language: cpp
sudo: required
compiler:
    - gcc
before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y freeglut3-dev
  - sudo apt-get install -y libsdl2-2.0
  - sudo apt-get install -y libsdl2-dev
script:
  - "./config.sh"
  - cd build
  - make