language: cpp
sudo: required
compiler:
    - gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y freeglut3-dev
install:
  # SDL2
  - curl -O http://www.libsdl.org/release/SDL2-2.0.5.tar.gz
  - tar -xzvf SDL2-2.0.0.tar.gz
  - (cd SDL2-2.0.0 && ./configure && make && sudo make install)
script:
  - "./config.sh"
  - cd build
  - make